# Generated by Django 3.2.12 on 2023-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
