# Generated by Django 3.2.12 on 2023-08-17 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='rated',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
