# Generated by Django 4.2.4 on 2023-08-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20230817_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='plan_images'),
        ),
    ]
