# Generated by Django 3.2.12 on 2023-08-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_alter_plan_plan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
