# Generated by Django 3.2.12 on 2023-08-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=2000)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
            ],
        ),
    ]
