# Generated by Django 3.2.12 on 2023-08-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
