# fly.toml app configuration file generated for lively-darkness-2264 on 2023-08-29T11:12:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lively-darkness-2264"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
